package com.github.fengdai.registry;

import android.support.annotation.NonNull;
import android.support.v7.widget.RecyclerView;
import android.view.ViewGroup;
import java.util.Collections;
import java.util.List;

/**
 * Delegate for RecyclerView.Adapter and it's subclasses to deal with items and ViewHolder creation.
 * <p>
 * Implementations of AdapterDelegate are generated by the processor for every
 * {@link Registry @Registry} types.
 */
public abstract class AdapterDelegate<ItemT extends RegistryItem> {

  /**
   * Called by RecyclerView.Adapter#onCreateViewHolder(ViewGroup, int).
   */
  @NonNull public abstract RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType);

  /**
   * Called by RecyclerView.Adapter#onBindViewHolder(RecyclerView.ViewHolder, int).
   */
  public final void onBindViewHolder(@NonNull RecyclerView.ViewHolder holder, ItemT item) {
    onBindViewHolder(holder, item, Collections.emptyList());
  }

  /**
   * Called by RecyclerView.Adapter#onBindViewHolder(RecyclerView.ViewHolder, int, List).
   */
  @SuppressWarnings("unchecked")
  public final void onBindViewHolder(@NonNull RecyclerView.ViewHolder holder, ItemT item, @NonNull List<Object> payloads) {
    if (item.getBinder() != null) {
      item.getBinder().bind(item.getData(), holder, payloads);
    }
  }

  /**
   * Called by RecyclerView.Adapter#getItemViewType(int).
   */
  public final int getItemViewType(ItemT item) {
    return item.getViewType();
  }
}
